const types = {
    GET_TASKS: "GET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    SET_OR_REMOVE_LOADING: "SET_OR_REMOVE_LOADING",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL: "TOGGLE_CHECK_ALL",
    EDIT: "EDIT",
    SET_EDIT_TASK: "SET_EDIT_TASK",
    GET_SINGLE_TASK: "GET_SINGLE_TASK",
    TOGGLE_EDIT_MODAL: "TOGGLE_EDIT_MODAL",
}

export default types;