export default Object.freeze(  {
    //global
    SET_OR_REMOVE_LOADING: "SET_OR_REMOVE_LOADING",
    GET_ERROR_MASSAGE:"GET_ERROR_MASSAGE",
    //local
    GET_TASKS: "GET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL: "TOGGLE_CHECK_ALL",
    EDIT: "EDIT",
    SET_EDIT_TASK: "SET_EDIT_TASK",
    GET_SINGLE_TASK: "GET_SINGLE_TASK",
    TOGGLE_EDIT_MODAL: "TOGGLE_EDIT_MODAL",
    CHANGE_CONTACT_FORM:"CHANGE_CONTACT_FORM",
    BACKEND_ERROR:"BACKEND_ERROR",
    GET_SUCCESS_MASSAGE:"GET_SUCCESS_MASSAGE",
    CHANGE_MODAL_INPUT:"CHANGE_MODAL_INPUT",
    CHANGE_MODAL_DATE:"CHANGE_MODAL_DATE",
    SET_EDITABLE_TASK_TO_MODAL_STATE:"SET_EDITABLE_TASK_TO_MODAL_STATE",
    RESET_TASK_MODAL:"RESET_TASK_MODAL",
    SET_ERROR_MESSAGE:"SET_ERROR_MESSAGE",
    SET_DROPDOWN_VARIANT:"SET_DROPDOWN_VARIANT",
    CHANGE_SEARCH_VALUE:"CHANGE_SEARCH_VALUE",
    SET_DATE:"SET_DATE",
    RESET_SEARCH_STATE:"RESET_SEARCH_STATE",

})

